# Generated by Django 2.2.7 on 2019-12-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='volunterSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'volunteer skills',
                'db_table': 'mst_volunteer_skills',
            },
        ),
    ]
