# Generated by Django 2.2.7 on 2019-12-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0002_volunterskills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunterskills',
            name='skills',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
