# Generated by Django 2.2.7 on 2019-12-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0003_auto_20191206_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerregistration',
            name='skills',
            field=models.ForeignKey(default=False, on_delete='cascade', to='volunteer.volunterSkills'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='volunterskills',
            name='skills',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
