# Generated by Django 2.2.7 on 2019-12-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0005_remove_volunteerregistration_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerregistration',
            name='skills',
            field=models.ForeignKey(default=2, on_delete='cascade', to='volunteer.volunterSkills'),
            preserve_default=False,
        ),
    ]
