# Generated by Django 2.2.7 on 2019-12-06 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0006_volunteerregistration_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerregistration',
            name='skills',
        ),
    ]
